#################################
# Backend
#################################

backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;

#################################
# Sync / Tearing
#################################

vsync = true;
use-damage = false;

#################################
# General
#################################

detect-client-opacity = true;
detect-transient = true;
detect-client-leader = true;

#################################
# Fading / Shadows (disabled)
#################################

fading = false;
shadow = false;

